### ISSUE TITLE
Weaviate Local

### ISSUE THREAD

**Issue by adlifuad-asc** [naaive/weaviate-ui#1]
I run Weaviate locally using docker,

My question is do we change the default port from '8080' to '8091' as per command that you give?

Or it is only for using Weaviate cloud?

**Comment by sweetcard** [comment]
Any port can be used including 8080 or any others

**Comment by jiangSunset** [comment]
Hello, may I ask why I still can't start the UI even though the real port is 8080 after executing this command.
docker run -e WEAVIATE_URL=http://localhost:8080 -e WEAVIATE_API_KEYS=secret naaive/weaviate-ui:latest.

Here are some error messages. Please help take a look. Thank you

  File "/usr/local/lib/python3.11/site-packages/weaviate/client.py", line 150, in __init__
    self._connection = Connection(
                       ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weaviate/connect/connection.py", line 163, in __init__
    self.wait_for_weaviate(startup_period)
  File "/usr/local/lib/python3.11/site-packages/weaviate/connect/connection.py", line 650, in wait_for_weaviate
    raise WeaviateStartUpError(
weaviate.exceptions.WeaviateStartUpError: Weaviate did not start up in 5 seconds. Either the Weaviate URL http://localhost:8080 is wrong or Weaviate did not start up in the interval given in 'startup_period'.

**Comment by Kurukshetran** [comment]
same issue with me as well

**Comment by lyfuci** [comment]
@Kurukshetran I think this error may caused by the version of weaviate version miss match. the client in this project is based on 3.x weaviate.

**Comment by noamsiegel** [comment]
@Kurukshetran @lyfuci Where you guys able to get it worked? Or are we waiting on the Weaviate team to finally make this front-end

**Comment by martincpt** [comment]
Same here. Would love to see a fix.

**Comment by ma3842** [comment]
Same issue

**Comment by martincpt** [comment]
If anyone interested I made a fix and migrated from the v3 client to the newer v4.

PR here: #2

**Comment by usersina** [comment]
Here's  a `docker-compose.yml` for prosperity's sake (with `unstructured-api` as a bonus)

```yaml
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.0
    restart: unless-stopped
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate-vol:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
    networks:
      - default-net

  weaviate-ui:
    image: naaive/weaviate-ui:latest
    restart: unless-stopped
    ports:
      - 7777:7777
    environment:
      WEAVIATE_URL: http://weaviate:8080
    networks:
      - default-net
    depends_on:
      - weaviate

  # https://github.com/Unstructured-IO/unstructured-api/issues/386
  unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:latest
    restart: unless-stopped
    ports:
      - '8000:8000' # Default API port for Unstructured
    # volumes:
    #   - ./data:/data # Optional volume for data processing
    networks:
      - default-net

volumes:
  weaviate-vol:
    driver: local

networks:
  default-net:
    name: default-network
    driver: bridge
```
